/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project.$projectId.index'
import { Route as ProjectProjectIdPdfRouteImport } from './routes/project.$projectId.pdf'
import { Route as ProjectProjectIdPhotoPhotoIdRouteImport } from './routes/project.$projectId.photo.$photoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdPdfRoute = ProjectProjectIdPdfRouteImport.update({
  id: '/pdf',
  path: '/pdf',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdPhotoPhotoIdRoute =
  ProjectProjectIdPhotoPhotoIdRouteImport.update({
    id: '/photo/$photoId',
    path: '/photo/$photoId',
    getParentRoute: () => ProjectProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/pdf': typeof ProjectProjectIdPdfRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/photo/$photoId': typeof ProjectProjectIdPhotoPhotoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project/$projectId/pdf': typeof ProjectProjectIdPdfRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/photo/$photoId': typeof ProjectProjectIdPhotoPhotoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/project/$projectId/pdf': typeof ProjectProjectIdPdfRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/project/$projectId/photo/$photoId': typeof ProjectProjectIdPhotoPhotoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/project/$projectId'
    | '/project/$projectId/pdf'
    | '/project/$projectId/'
    | '/project/$projectId/photo/$photoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/project/$projectId/pdf'
    | '/project/$projectId'
    | '/project/$projectId/photo/$photoId'
  id:
    | '__root__'
    | '/'
    | '/project/$projectId'
    | '/project/$projectId/pdf'
    | '/project/$projectId/'
    | '/project/$projectId/photo/$photoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/pdf': {
      id: '/project/$projectId/pdf'
      path: '/pdf'
      fullPath: '/project/$projectId/pdf'
      preLoaderRoute: typeof ProjectProjectIdPdfRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/photo/$photoId': {
      id: '/project/$projectId/photo/$photoId'
      path: '/photo/$photoId'
      fullPath: '/project/$projectId/photo/$photoId'
      preLoaderRoute: typeof ProjectProjectIdPhotoPhotoIdRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
  }
}

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdPdfRoute: typeof ProjectProjectIdPdfRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
  ProjectProjectIdPhotoPhotoIdRoute: typeof ProjectProjectIdPhotoPhotoIdRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdPdfRoute: ProjectProjectIdPdfRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
  ProjectProjectIdPhotoPhotoIdRoute: ProjectProjectIdPhotoPhotoIdRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
